name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout

jobs:

  build:

    runs-on: ubuntu-latest
    steps:
          - uses: actions/checkout@v3 
          - name: configure aws credentials
            uses: aws-actions/configure-aws-credentials@v4
            with:
              role-to-assume: arn:aws:iam::510837106682:role/github-ecr-role
              # role-session-name: samplerolesession
              aws-region: 'us-west-1'
    
          - name: Login to Amazon ECR
            id: login-ecr
            uses: aws-actions/amazon-ecr-login@v2

          - name: Build, tag, and push docker image to Amazon ECR
            env:
              REGISTRY: ${{ steps.login-ecr.outputs.registry }}
              REPOSITORY: ${{ secrets.REPOSITORY }}
              IMAGE_TAG: $(calculatedSha=$(git rev-parse --short ${{ github.sha }}))
            run: |
              ls -la
              docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
              docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
