name: Peer market K8s
on:
  workflow_call:
    inputs:
      ECR_REPOSITORY:
        description: 'The Amazon ECR repository name used for pushing images to the UAT or production ECR'
        required: true
        type: string
      AWS_REGION:
        description: 'aws region'
        required: true
        type: string
      ARGOCD_BRANCH:
        description: 'ArgoCD branch for cloning based on environment (uat or prod)'
        required: true
        type: string
    secrets:
      ROLE:
        description: 'AWS role for pushing images to an ECR registry'
        required: true
      GIT_SSH_KEY:
        description: 'GitHub Actions use a SSH key for cloning the ArgoCD repository.'
        required: true
      
permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout

jobs:
  deploy-peermarket-web:
    runs-on: ubuntu-latest
    # permissions: write-all
    steps:
          - name: Check out repository
            uses: actions/checkout@v4
              
          - name: configure aws credentials
            uses: aws-actions/configure-aws-credentials@v4
            with:
              role-to-assume: ${{ secrets.ROLE }}
              aws-region: ${{ inputs.AWS_REGION }}
    
          - name: Login to Amazon ECR
            id: login-ecr
            uses: aws-actions/amazon-ecr-login@v2

#############          
# Build Image
#############
          - name: Build, tag, and push docker image to Amazon ECR
            env:
              REGISTRY: ${{ steps.login-ecr.outputs.registry }}
              ECR_REPOSITORY: ${{ inputs.ECR_REPOSITORY }}
              IMAGE_TAG: ${{ github.sha  }}
            run: |
              SHORT_SHA=$(echo "${IMAGE_TAG}" | cut -c1-7)
              docker build --no-cache -t $REGISTRY/$ECR_REPOSITORY:$SHORT_SHA .
              docker push $REGISTRY/$ECR_REPOSITORY:$SHORT_SHA  
              echo "REGISTRY=$REGISTRY" >> $GITHUB_ENV
              echo "ECR_REPOSITORY=$ECR_REPOSITORY" >> $GITHUB_ENV
              echo "IMAGE_TAG=$SHORT_SHA" >> $GITHUB_ENV

################         
# Update argocd
################
          - name: "Update image tag in argocd repository"
            uses: actions/checkout@v4
            with:
              repository: ajaykumar1007/argocd
              ref: ${{ inputs.ARGOCD_BRANCH }}
              ssh-key: ${{ secrets.SS }}
            env:
              REGISTRY: ${{ steps.login-ecr.outputs.registry }}
              ECR_REPOSITORY: ${{ inputs.ECR_REPOSITORY }}
          - run: |
              git config user.name github-actions
              git config user.email github-actions@github.com 
              cd stage
              image_url=$(sed -n 's/.*\(image:\)/\1/p' deployment.yaml|cut -d' ' -f2)
              sed  -i s+${image_url}+$REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG+g deployment.yaml
              git add .
              git commit -m "image update"
              git push origin 
