name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout

jobs:

  build:

    runs-on: ubuntu-latest
    steps:
          - name: Check out repository
            uses: actions/checkout@v4

          - name: Set variable based on branch
            run: |
              if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
              echo "REGION=us-west-1" >> $GITHUB_ENV
              elif [[ "${{ github.ref }}" == "refs/heads/test" ]]; then
              echo "REGION=us-west-1" >> $GITHUB_ENV
              else
                echo "Unsupported branch."
                exit 1
              fi
              
          - name: configure aws credentials
            uses: aws-actions/configure-aws-credentials@v4
            with:
              role-to-assume: ${{ secrets.ROLE }}
              aws-region: ${{ env.REGION }}
    
          - name: Login to Amazon ECR
            id: login-ecr
            uses: aws-actions/amazon-ecr-login@v2

          - name: Build, tag, and push docker image to Amazon ECR
            env:
              REGISTRY: ${{ steps.login-ecr.outputs.registry }}
              REPOSITORY: ${{ secrets.REPOSITORY }}
              IMAGE_TAG: ${{ github.sha  }}
            run: |
              # SHORT_SHA=$(echo "${IMAGE_TAG}" | cut -c1-7)
              docker build --no-cache -t $REGISTRY/$REPOSITORY:$SHORT_SHA .
              docker push $REGISTRY/$REPOSITORY:$SHORT_SHA

          # - uses: 8398a7/action-slack@v3
          #   with:
          #     status: ${{ job.status }}
          #     fields: repo,commit,author,ref # selectable (default: repo,message)
          #   env:
          #     SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
          #   if: always() # Pick up events even if the job fails or is canceled
          - name: Send custom JSON data to Slack workflow
            id: slack
            uses: slackapi/slack-github-action@v1.26.0
            with:
              status: ${{ job.status }}
              fields: repo,commit,author,ref # selectable (default: repo,message)
            env:
              SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
            if: always() # Pick up events even if the job fails or is canceled.

