name: '[uat] Deploy Peermarket web app'

# As the UAT and production deployments are handled by codepipeline, this workflow is not used
# on: workflow_dispatch # Allows manual triggering of workflow
#   push:
#     branches: 
#       - v1-stable
on:
  push:
    branches: 
      - stage

jobs:
  uat_deploy_peermarket:
    uses: ./.github/workflows/docker-image.yml
    with:
      ECR_REPOSITORY: test121
      AWS_REGION: us-east-2
      ARGOCD_BRANCH: 'stage'
      # PATH: 'stage'
    secrets:
      ROLE: ${{ secrets.ROLE }}
      TOKO: ${{ secrets.TOKO }}
